-- Layer 2 cutover wipe SQL for MS Vallee test-site reset.
-- Generated by scripts/cutover_generate_wipe_sql.py.
-- Source manifest: supabase/manual/cutover/manifest.yaml
-- Do not edit by hand; regenerate from manifest and review before execution.
--
-- This file is destructive. It is only executed at RUNBOOK.md step 5,
-- after QA and preservation exports have completed and the operator has
-- confirmed: PROCEED LAYER 2 WIPE FOR MS VALLEE TEST SITE

\set ON_ERROR_STOP on

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '10min';
SET LOCAL application_name = 'onyx_layer2_cutover_wipe';

-- Preflight: refuse if the live FK shape does not match the reviewed manifest assumptions.
DO $wipe_preflight$
DECLARE
    missing text;
    unexpected text;
    empty_ref record;
    empty_count bigint;
BEGIN
    WITH wipe(label, regclass_name) AS (
        VALUES
        ('public.actions_log', '"public"."actions_log"'),
        ('public.incident_intelligence', '"public"."incident_intelligence"'),
        ('public.incident_outcomes', '"public"."incident_outcomes"'),
        ('public.incident_snapshots', '"public"."incident_snapshots"'),
        ('public.dispatch_transitions', '"public"."dispatch_transitions"'),
        ('public.evidence_bundles', '"public"."evidence_bundles"'),
        ('public.execution_locks', '"public"."execution_locks"'),
        ('public.guard_ops_media', '"public"."guard_ops_media"'),
        ('public.guard_ops_retention_runs', '"public"."guard_ops_retention_runs"'),
        ('public.patrol_violations', '"public"."patrol_violations"'),
        ('public.patrol_triggers', '"public"."patrol_triggers"'),
        ('public.patrol_scans', '"public"."patrol_scans"'),
        ('public.patrol_checkpoints', '"public"."patrol_checkpoints"'),
        ('public.logs', '"public"."logs"'),
        ('public.users', '"public"."users"'),
        ('public.zara_action_log', '"public"."zara_action_log"'),
        ('public.ThreatMatrix', '"public"."ThreatMatrix"'),
        ('public.employee_site_assignments', '"public"."employee_site_assignments"'),
        ('public.guard_documents', '"public"."guard_documents"'),
        ('public.guard_profiles', '"public"."guard_profiles"'),
        ('public.guard_sites', '"public"."guard_sites"'),
        ('public.incidents', '"public"."incidents"'),
        ('public.dispatch_intents', '"public"."dispatch_intents"'),
        ('public.guard_ops_events', '"public"."guard_ops_events"'),
        ('public.guard_projection_retention_runs', '"public"."guard_projection_retention_runs"'),
        ('public.guard_ops_replay_safety_checks', '"public"."guard_ops_replay_safety_checks"'),
        ('public.patrols', '"public"."patrols"'),
        ('public.patrol_routes', '"public"."patrol_routes"'),
        ('public.roles', '"public"."roles"'),
        ('public.ThreatLevels', '"public"."ThreatLevels"'),
        ('public.ThreatCategories', '"public"."ThreatCategories"'),
        ('public.zara_scenarios', '"public"."zara_scenarios"'),
        ('public.employees', '"public"."employees"'),
        ('public.guards', '"public"."guards"'),
        ('public.abort_logs', '"public"."abort_logs"'),
        ('public.alert_events', '"public"."alert_events"'),
        ('public.civic_events', '"public"."civic_events"'),
        ('public.client_conversation_acknowledgements', '"public"."client_conversation_acknowledgements"'),
        ('public.client_conversation_messages', '"public"."client_conversation_messages"'),
        ('public.client_conversation_push_queue', '"public"."client_conversation_push_queue"'),
        ('public.client_evidence_ledger', '"public"."client_evidence_ledger"'),
        ('public.command_events', '"public"."command_events"'),
        ('public.command_summaries', '"public"."command_summaries"'),
        ('public.decision_audit_log', '"public"."decision_audit_log"'),
        ('public.decision_traces', '"public"."decision_traces"'),
        ('public.escalation_events', '"public"."escalation_events"'),
        ('public.external_signals', '"public"."external_signals"'),
        ('public.global_clusters', '"public"."global_clusters"'),
        ('public.global_events', '"public"."global_events"'),
        ('public.guard_checkpoint_scans', '"public"."guard_checkpoint_scans"'),
        ('public.guard_incident_captures', '"public"."guard_incident_captures"'),
        ('public.guard_location_heartbeats', '"public"."guard_location_heartbeats"'),
        ('public.guard_logs', '"public"."guard_logs"'),
        ('public.guard_panic_signals', '"public"."guard_panic_signals"'),
        ('public.guard_sync_operations', '"public"."guard_sync_operations"'),
        ('public.hourly_throughput', '"public"."hourly_throughput"'),
        ('public.incident_actions', '"public"."incident_actions"'),
        ('public.incident_aar_scores', '"public"."incident_aar_scores"'),
        ('public.incident_replay_events', '"public"."incident_replay_events"'),
        ('public.incident_replays', '"public"."incident_replays"'),
        ('public.intel_events', '"public"."intel_events"'),
        ('public.intel_patrol_links', '"public"."intel_patrol_links"'),
        ('public.intelligence_snapshots', '"public"."intelligence_snapshots"'),
        ('public.keyword_escalations', '"public"."keyword_escalations"'),
        ('public.omnix_logs', '"public"."omnix_logs"'),
        ('public.onyx_alert_outcomes', '"public"."onyx_alert_outcomes"'),
        ('public.onyx_awareness_latency', '"public"."onyx_awareness_latency"'),
        ('public.onyx_client_trust_snapshots', '"public"."onyx_client_trust_snapshots"'),
        ('public.onyx_event_store', '"public"."onyx_event_store"'),
        ('public.onyx_evidence_certificates', '"public"."onyx_evidence_certificates"'),
        ('public.onyx_operator_scores', '"public"."onyx_operator_scores"'),
        ('public.onyx_operator_simulations', '"public"."onyx_operator_simulations"'),
        ('public.onyx_power_mode_events', '"public"."onyx_power_mode_events"'),
        ('public.ops_orders', '"public"."ops_orders"'),
        ('public.patrol_checkpoint_scans', '"public"."patrol_checkpoint_scans"'),
        ('public.patrol_compliance', '"public"."patrol_compliance"'),
        ('public.patrol_route_cooldowns', '"public"."patrol_route_cooldowns"'),
        ('public.patrol_route_recommendations', '"public"."patrol_route_recommendations"'),
        ('public.regional_risk_snapshots', '"public"."regional_risk_snapshots"'),
        ('public.site_alarm_events', '"public"."site_alarm_events"'),
        ('public.site_awareness_snapshots', '"public"."site_awareness_snapshots"'),
        ('public.site_occupancy_sessions', '"public"."site_occupancy_sessions"'),
        ('public.telegram_inbound_updates', '"public"."telegram_inbound_updates"'),
        ('public.threats', '"public"."threats"'),
        ('public.threat_scores', '"public"."threat_scores"'),
        ('public.vehicle_logs', '"public"."vehicle_logs"'),
        ('public.vehicle_visits', '"public"."vehicle_visits"'),
        ('public.violations', '"public"."violations"'),
        ('public.watch_archive', '"public"."watch_archive"'),
        ('public.watch_events', '"public"."watch_events"'),
        ('public.threat_decay_profiles', '"public"."threat_decay_profiles"'),
        ('public.alert_rules', '"public"."alert_rules"'),
        ('public.dispatch_actions', '"public"."dispatch_actions"'),
        ('public.mo_library', '"public"."mo_library"'),
        ('public.intel_source_weights', '"public"."intel_source_weights"'),
        ('public.global_patterns', '"public"."global_patterns"'),
        ('public.posts', '"public"."posts"'),
        ('public.staff', '"public"."staff"'),
        ('public.controllers', '"public"."controllers"'),
        ('public.guard_assignments', '"public"."guard_assignments"'),
        ('public.operational_nodes', '"public"."operational_nodes"'),
        ('public.duty_states', '"public"."duty_states"')
    )
    SELECT string_agg(label, ', ' ORDER BY label)
    INTO missing
    FROM wipe
    WHERE to_regclass(regclass_name) IS NULL;

    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'Wipe preflight failed; missing wipe tables: %', missing;
    END IF;

    WITH truncate_tables(label, regclass_name) AS (
        VALUES
        ('public.actions_log', '"public"."actions_log"'),
        ('public.incident_intelligence', '"public"."incident_intelligence"'),
        ('public.incident_outcomes', '"public"."incident_outcomes"'),
        ('public.incident_snapshots', '"public"."incident_snapshots"'),
        ('public.dispatch_transitions', '"public"."dispatch_transitions"'),
        ('public.evidence_bundles', '"public"."evidence_bundles"'),
        ('public.execution_locks', '"public"."execution_locks"'),
        ('public.guard_ops_media', '"public"."guard_ops_media"'),
        ('public.guard_ops_retention_runs', '"public"."guard_ops_retention_runs"'),
        ('public.patrol_violations', '"public"."patrol_violations"'),
        ('public.patrol_scans', '"public"."patrol_scans"'),
        ('public.patrol_checkpoints', '"public"."patrol_checkpoints"'),
        ('public.logs', '"public"."logs"'),
        ('public.users', '"public"."users"'),
        ('public.zara_action_log', '"public"."zara_action_log"'),
        ('public.ThreatMatrix', '"public"."ThreatMatrix"'),
        ('public.employee_site_assignments', '"public"."employee_site_assignments"'),
        ('public.guard_documents', '"public"."guard_documents"'),
        ('public.guard_profiles', '"public"."guard_profiles"'),
        ('public.guard_sites', '"public"."guard_sites"'),
        ('public.incidents', '"public"."incidents"'),
        ('public.dispatch_intents', '"public"."dispatch_intents"'),
        ('public.guard_ops_events', '"public"."guard_ops_events"'),
        ('public.guard_projection_retention_runs', '"public"."guard_projection_retention_runs"'),
        ('public.guard_ops_replay_safety_checks', '"public"."guard_ops_replay_safety_checks"'),
        ('public.patrol_routes', '"public"."patrol_routes"'),
        ('public.roles', '"public"."roles"'),
        ('public.ThreatLevels', '"public"."ThreatLevels"'),
        ('public.ThreatCategories', '"public"."ThreatCategories"'),
        ('public.zara_scenarios', '"public"."zara_scenarios"'),
        ('public.abort_logs', '"public"."abort_logs"'),
        ('public.alert_events', '"public"."alert_events"'),
        ('public.civic_events', '"public"."civic_events"'),
        ('public.client_conversation_acknowledgements', '"public"."client_conversation_acknowledgements"'),
        ('public.client_conversation_messages', '"public"."client_conversation_messages"'),
        ('public.client_conversation_push_queue', '"public"."client_conversation_push_queue"'),
        ('public.client_evidence_ledger', '"public"."client_evidence_ledger"'),
        ('public.command_events', '"public"."command_events"'),
        ('public.command_summaries', '"public"."command_summaries"'),
        ('public.decision_audit_log', '"public"."decision_audit_log"'),
        ('public.decision_traces', '"public"."decision_traces"'),
        ('public.escalation_events', '"public"."escalation_events"'),
        ('public.external_signals', '"public"."external_signals"'),
        ('public.global_clusters', '"public"."global_clusters"'),
        ('public.global_events', '"public"."global_events"'),
        ('public.guard_checkpoint_scans', '"public"."guard_checkpoint_scans"'),
        ('public.guard_incident_captures', '"public"."guard_incident_captures"'),
        ('public.guard_location_heartbeats', '"public"."guard_location_heartbeats"'),
        ('public.guard_logs', '"public"."guard_logs"'),
        ('public.guard_panic_signals', '"public"."guard_panic_signals"'),
        ('public.guard_sync_operations', '"public"."guard_sync_operations"'),
        ('public.hourly_throughput', '"public"."hourly_throughput"'),
        ('public.incident_actions', '"public"."incident_actions"'),
        ('public.incident_aar_scores', '"public"."incident_aar_scores"'),
        ('public.incident_replay_events', '"public"."incident_replay_events"'),
        ('public.incident_replays', '"public"."incident_replays"'),
        ('public.intel_events', '"public"."intel_events"'),
        ('public.intel_patrol_links', '"public"."intel_patrol_links"'),
        ('public.intelligence_snapshots', '"public"."intelligence_snapshots"'),
        ('public.keyword_escalations', '"public"."keyword_escalations"'),
        ('public.omnix_logs', '"public"."omnix_logs"'),
        ('public.onyx_alert_outcomes', '"public"."onyx_alert_outcomes"'),
        ('public.onyx_awareness_latency', '"public"."onyx_awareness_latency"'),
        ('public.onyx_client_trust_snapshots', '"public"."onyx_client_trust_snapshots"'),
        ('public.onyx_event_store', '"public"."onyx_event_store"'),
        ('public.onyx_evidence_certificates', '"public"."onyx_evidence_certificates"'),
        ('public.onyx_operator_scores', '"public"."onyx_operator_scores"'),
        ('public.onyx_operator_simulations', '"public"."onyx_operator_simulations"'),
        ('public.onyx_power_mode_events', '"public"."onyx_power_mode_events"'),
        ('public.ops_orders', '"public"."ops_orders"'),
        ('public.patrol_checkpoint_scans', '"public"."patrol_checkpoint_scans"'),
        ('public.patrol_compliance', '"public"."patrol_compliance"'),
        ('public.patrol_route_cooldowns', '"public"."patrol_route_cooldowns"'),
        ('public.patrol_route_recommendations', '"public"."patrol_route_recommendations"'),
        ('public.regional_risk_snapshots', '"public"."regional_risk_snapshots"'),
        ('public.site_alarm_events', '"public"."site_alarm_events"'),
        ('public.site_awareness_snapshots', '"public"."site_awareness_snapshots"'),
        ('public.site_occupancy_sessions', '"public"."site_occupancy_sessions"'),
        ('public.telegram_inbound_updates', '"public"."telegram_inbound_updates"'),
        ('public.threats', '"public"."threats"'),
        ('public.threat_scores', '"public"."threat_scores"'),
        ('public.vehicle_logs', '"public"."vehicle_logs"'),
        ('public.vehicle_visits', '"public"."vehicle_visits"'),
        ('public.violations', '"public"."violations"'),
        ('public.watch_archive', '"public"."watch_archive"'),
        ('public.watch_events', '"public"."watch_events"'),
        ('public.threat_decay_profiles', '"public"."threat_decay_profiles"'),
        ('public.alert_rules', '"public"."alert_rules"'),
        ('public.dispatch_actions', '"public"."dispatch_actions"'),
        ('public.mo_library', '"public"."mo_library"'),
        ('public.intel_source_weights', '"public"."intel_source_weights"'),
        ('public.global_patterns', '"public"."global_patterns"'),
        ('public.staff', '"public"."staff"'),
        ('public.controllers', '"public"."controllers"'),
        ('public.guard_assignments', '"public"."guard_assignments"'),
        ('public.operational_nodes', '"public"."operational_nodes"'),
        ('public.duty_states', '"public"."duty_states"')
    )
    SELECT string_agg(format('%s -> %s (%s)', c.conrelid::regclass, c.confrelid::regclass, c.conname), E'\n')
    INTO unexpected
    FROM pg_constraint c
    JOIN truncate_tables target ON c.confrelid = to_regclass(target.regclass_name)
    WHERE c.contype = 'f'
      AND NOT EXISTS (
          SELECT 1
          FROM truncate_tables source
          WHERE c.conrelid = to_regclass(source.regclass_name)
      );

    IF unexpected IS NOT NULL THEN
        RAISE EXCEPTION 'Unsafe TRUNCATE target: external FK(s) reference truncate tables:%', E'\n' || unexpected;
    END IF;

    WITH delete_tables(label, regclass_name) AS (
        VALUES
        ('public.patrol_triggers', '"public"."patrol_triggers"'),
        ('public.patrols', '"public"."patrols"'),
        ('public.employees', '"public"."employees"'),
        ('public.guards', '"public"."guards"'),
        ('public.posts', '"public"."posts"')
    ),
    wipe(label, regclass_name) AS (
        VALUES
        ('public.actions_log', '"public"."actions_log"'),
        ('public.incident_intelligence', '"public"."incident_intelligence"'),
        ('public.incident_outcomes', '"public"."incident_outcomes"'),
        ('public.incident_snapshots', '"public"."incident_snapshots"'),
        ('public.dispatch_transitions', '"public"."dispatch_transitions"'),
        ('public.evidence_bundles', '"public"."evidence_bundles"'),
        ('public.execution_locks', '"public"."execution_locks"'),
        ('public.guard_ops_media', '"public"."guard_ops_media"'),
        ('public.guard_ops_retention_runs', '"public"."guard_ops_retention_runs"'),
        ('public.patrol_violations', '"public"."patrol_violations"'),
        ('public.patrol_triggers', '"public"."patrol_triggers"'),
        ('public.patrol_scans', '"public"."patrol_scans"'),
        ('public.patrol_checkpoints', '"public"."patrol_checkpoints"'),
        ('public.logs', '"public"."logs"'),
        ('public.users', '"public"."users"'),
        ('public.zara_action_log', '"public"."zara_action_log"'),
        ('public.ThreatMatrix', '"public"."ThreatMatrix"'),
        ('public.employee_site_assignments', '"public"."employee_site_assignments"'),
        ('public.guard_documents', '"public"."guard_documents"'),
        ('public.guard_profiles', '"public"."guard_profiles"'),
        ('public.guard_sites', '"public"."guard_sites"'),
        ('public.incidents', '"public"."incidents"'),
        ('public.dispatch_intents', '"public"."dispatch_intents"'),
        ('public.guard_ops_events', '"public"."guard_ops_events"'),
        ('public.guard_projection_retention_runs', '"public"."guard_projection_retention_runs"'),
        ('public.guard_ops_replay_safety_checks', '"public"."guard_ops_replay_safety_checks"'),
        ('public.patrols', '"public"."patrols"'),
        ('public.patrol_routes', '"public"."patrol_routes"'),
        ('public.roles', '"public"."roles"'),
        ('public.ThreatLevels', '"public"."ThreatLevels"'),
        ('public.ThreatCategories', '"public"."ThreatCategories"'),
        ('public.zara_scenarios', '"public"."zara_scenarios"'),
        ('public.employees', '"public"."employees"'),
        ('public.guards', '"public"."guards"'),
        ('public.abort_logs', '"public"."abort_logs"'),
        ('public.alert_events', '"public"."alert_events"'),
        ('public.civic_events', '"public"."civic_events"'),
        ('public.client_conversation_acknowledgements', '"public"."client_conversation_acknowledgements"'),
        ('public.client_conversation_messages', '"public"."client_conversation_messages"'),
        ('public.client_conversation_push_queue', '"public"."client_conversation_push_queue"'),
        ('public.client_evidence_ledger', '"public"."client_evidence_ledger"'),
        ('public.command_events', '"public"."command_events"'),
        ('public.command_summaries', '"public"."command_summaries"'),
        ('public.decision_audit_log', '"public"."decision_audit_log"'),
        ('public.decision_traces', '"public"."decision_traces"'),
        ('public.escalation_events', '"public"."escalation_events"'),
        ('public.external_signals', '"public"."external_signals"'),
        ('public.global_clusters', '"public"."global_clusters"'),
        ('public.global_events', '"public"."global_events"'),
        ('public.guard_checkpoint_scans', '"public"."guard_checkpoint_scans"'),
        ('public.guard_incident_captures', '"public"."guard_incident_captures"'),
        ('public.guard_location_heartbeats', '"public"."guard_location_heartbeats"'),
        ('public.guard_logs', '"public"."guard_logs"'),
        ('public.guard_panic_signals', '"public"."guard_panic_signals"'),
        ('public.guard_sync_operations', '"public"."guard_sync_operations"'),
        ('public.hourly_throughput', '"public"."hourly_throughput"'),
        ('public.incident_actions', '"public"."incident_actions"'),
        ('public.incident_aar_scores', '"public"."incident_aar_scores"'),
        ('public.incident_replay_events', '"public"."incident_replay_events"'),
        ('public.incident_replays', '"public"."incident_replays"'),
        ('public.intel_events', '"public"."intel_events"'),
        ('public.intel_patrol_links', '"public"."intel_patrol_links"'),
        ('public.intelligence_snapshots', '"public"."intelligence_snapshots"'),
        ('public.keyword_escalations', '"public"."keyword_escalations"'),
        ('public.omnix_logs', '"public"."omnix_logs"'),
        ('public.onyx_alert_outcomes', '"public"."onyx_alert_outcomes"'),
        ('public.onyx_awareness_latency', '"public"."onyx_awareness_latency"'),
        ('public.onyx_client_trust_snapshots', '"public"."onyx_client_trust_snapshots"'),
        ('public.onyx_event_store', '"public"."onyx_event_store"'),
        ('public.onyx_evidence_certificates', '"public"."onyx_evidence_certificates"'),
        ('public.onyx_operator_scores', '"public"."onyx_operator_scores"'),
        ('public.onyx_operator_simulations', '"public"."onyx_operator_simulations"'),
        ('public.onyx_power_mode_events', '"public"."onyx_power_mode_events"'),
        ('public.ops_orders', '"public"."ops_orders"'),
        ('public.patrol_checkpoint_scans', '"public"."patrol_checkpoint_scans"'),
        ('public.patrol_compliance', '"public"."patrol_compliance"'),
        ('public.patrol_route_cooldowns', '"public"."patrol_route_cooldowns"'),
        ('public.patrol_route_recommendations', '"public"."patrol_route_recommendations"'),
        ('public.regional_risk_snapshots', '"public"."regional_risk_snapshots"'),
        ('public.site_alarm_events', '"public"."site_alarm_events"'),
        ('public.site_awareness_snapshots', '"public"."site_awareness_snapshots"'),
        ('public.site_occupancy_sessions', '"public"."site_occupancy_sessions"'),
        ('public.telegram_inbound_updates', '"public"."telegram_inbound_updates"'),
        ('public.threats', '"public"."threats"'),
        ('public.threat_scores', '"public"."threat_scores"'),
        ('public.vehicle_logs', '"public"."vehicle_logs"'),
        ('public.vehicle_visits', '"public"."vehicle_visits"'),
        ('public.violations', '"public"."violations"'),
        ('public.watch_archive', '"public"."watch_archive"'),
        ('public.watch_events', '"public"."watch_events"'),
        ('public.threat_decay_profiles', '"public"."threat_decay_profiles"'),
        ('public.alert_rules', '"public"."alert_rules"'),
        ('public.dispatch_actions', '"public"."dispatch_actions"'),
        ('public.mo_library', '"public"."mo_library"'),
        ('public.intel_source_weights', '"public"."intel_source_weights"'),
        ('public.global_patterns', '"public"."global_patterns"'),
        ('public.posts', '"public"."posts"'),
        ('public.staff', '"public"."staff"'),
        ('public.controllers', '"public"."controllers"'),
        ('public.guard_assignments', '"public"."guard_assignments"'),
        ('public.operational_nodes', '"public"."operational_nodes"'),
        ('public.duty_states', '"public"."duty_states"')
    ),
    expected_external(source_label, source_regclass_name, target_label, target_regclass_name, required_confdeltype) AS (
        VALUES
        ('public.vehicles', '"public"."vehicles"', 'public.employees', '"public"."employees"', 'n'),
        ('public.deployments', '"public"."deployments"', 'public.guards', '"public"."guards"', ''),
        ('public.checkins', '"public"."checkins"', 'public.patrol_triggers', '"public"."patrol_triggers"', ''),
        ('public.checkins', '"public"."checkins"', 'public.posts', '"public"."posts"', '')
    )
    SELECT string_agg(format('%s -> %s (%s)', c.conrelid::regclass, c.confrelid::regclass, c.conname), E'\n')
    INTO unexpected
    FROM pg_constraint c
    JOIN delete_tables target ON c.confrelid = to_regclass(target.regclass_name)
    WHERE c.contype = 'f'
      AND NOT EXISTS (
          SELECT 1
          FROM wipe source
          WHERE c.conrelid = to_regclass(source.regclass_name)
      )
      AND NOT EXISTS (
          SELECT 1
          FROM expected_external expected
          WHERE c.conrelid = to_regclass(expected.source_regclass_name)
            AND c.confrelid = to_regclass(expected.target_regclass_name)
      );

    IF unexpected IS NOT NULL THEN
        RAISE EXCEPTION 'Unsafe DELETE target: unexpected external FK(s) reference delete tables:%', E'\n' || unexpected;
    END IF;

    WITH expected_external(source_label, source_regclass_name, target_label, target_regclass_name, required_confdeltype) AS (
        VALUES
        ('public.vehicles', '"public"."vehicles"', 'public.employees', '"public"."employees"', 'n'),
        ('public.deployments', '"public"."deployments"', 'public.guards', '"public"."guards"', ''),
        ('public.checkins', '"public"."checkins"', 'public.patrol_triggers', '"public"."patrol_triggers"', ''),
        ('public.checkins', '"public"."checkins"', 'public.posts', '"public"."posts"', '')
    )
    SELECT string_agg(
        CASE
            WHEN c.oid IS NULL THEN
                format('%s -> %s (missing expected FK)', expected.source_label, expected.target_label)
            ELSE
                format('%s -> %s (%s) delete_action=%s', c.conrelid::regclass, c.confrelid::regclass, c.conname, c.confdeltype)
        END,
        E'\n'
    )
    INTO unexpected
    FROM expected_external expected
    LEFT JOIN pg_constraint c
      ON c.conrelid = to_regclass(expected.source_regclass_name)
     AND c.confrelid = to_regclass(expected.target_regclass_name)
     AND c.contype = 'f'
    WHERE c.oid IS NULL
       OR (expected.required_confdeltype <> '' AND c.confdeltype <> expected.required_confdeltype);

    IF unexpected IS NOT NULL THEN
        RAISE EXCEPTION 'Expected external FK missing or delete action mismatch:%', E'\n' || unexpected;
    END IF;

    FOR empty_ref IN
        WITH expected_empty(source_label, source_regclass_name, column_label) AS (
        VALUES
        ('public.checkins', '"public"."checkins"', 'public.checkins.patrol_trigger_id'),
        ('public.checkins', '"public"."checkins"', 'public.checkins.post_id'),
        ('public.deployments', '"public"."deployments"', 'public.deployments.guard_id')
        )
        SELECT source_label, source_regclass_name, column_label
        FROM expected_empty
    LOOP
        EXECUTE format('SELECT count(*) FROM %s', empty_ref.source_regclass_name) INTO empty_count;
        IF empty_count <> 0 THEN
            RAISE EXCEPTION
                'Untouched table % must be empty before deleting wipe parent via %; found % row(s)',
                empty_ref.source_label,
                empty_ref.column_label,
                empty_count;
        END IF;
    END LOOP;
END
$wipe_preflight$;

-- Preserve public.vehicles while wiping public.employees: null the FK column first.
WITH updated AS (
    UPDATE "public"."vehicles"
    SET "assigned_employee_id" = NULL
    WHERE "assigned_employee_id" IS NOT NULL
    RETURNING 1
)
SELECT 'public.vehicles.assigned_employee_id nulled' AS action, count(*) AS rows FROM updated;

-- Truncate 97 wipe tables. No CASCADE: external FK preflight above must pass first.
TRUNCATE TABLE
    "public"."actions_log",
    "public"."incident_intelligence",
    "public"."incident_outcomes",
    "public"."incident_snapshots",
    "public"."dispatch_transitions",
    "public"."evidence_bundles",
    "public"."execution_locks",
    "public"."guard_ops_media",
    "public"."guard_ops_retention_runs",
    "public"."patrol_violations",
    "public"."patrol_scans",
    "public"."patrol_checkpoints",
    "public"."logs",
    "public"."users",
    "public"."zara_action_log",
    "public"."ThreatMatrix",
    "public"."employee_site_assignments",
    "public"."guard_documents",
    "public"."guard_profiles",
    "public"."guard_sites",
    "public"."incidents",
    "public"."dispatch_intents",
    "public"."guard_ops_events",
    "public"."guard_projection_retention_runs",
    "public"."guard_ops_replay_safety_checks",
    "public"."patrol_routes",
    "public"."roles",
    "public"."ThreatLevels",
    "public"."ThreatCategories",
    "public"."zara_scenarios",
    "public"."abort_logs",
    "public"."alert_events",
    "public"."civic_events",
    "public"."client_conversation_acknowledgements",
    "public"."client_conversation_messages",
    "public"."client_conversation_push_queue",
    "public"."client_evidence_ledger",
    "public"."command_events",
    "public"."command_summaries",
    "public"."decision_audit_log",
    "public"."decision_traces",
    "public"."escalation_events",
    "public"."external_signals",
    "public"."global_clusters",
    "public"."global_events",
    "public"."guard_checkpoint_scans",
    "public"."guard_incident_captures",
    "public"."guard_location_heartbeats",
    "public"."guard_logs",
    "public"."guard_panic_signals",
    "public"."guard_sync_operations",
    "public"."hourly_throughput",
    "public"."incident_actions",
    "public"."incident_aar_scores",
    "public"."incident_replay_events",
    "public"."incident_replays",
    "public"."intel_events",
    "public"."intel_patrol_links",
    "public"."intelligence_snapshots",
    "public"."keyword_escalations",
    "public"."omnix_logs",
    "public"."onyx_alert_outcomes",
    "public"."onyx_awareness_latency",
    "public"."onyx_client_trust_snapshots",
    "public"."onyx_event_store",
    "public"."onyx_evidence_certificates",
    "public"."onyx_operator_scores",
    "public"."onyx_operator_simulations",
    "public"."onyx_power_mode_events",
    "public"."ops_orders",
    "public"."patrol_checkpoint_scans",
    "public"."patrol_compliance",
    "public"."patrol_route_cooldowns",
    "public"."patrol_route_recommendations",
    "public"."regional_risk_snapshots",
    "public"."site_alarm_events",
    "public"."site_awareness_snapshots",
    "public"."site_occupancy_sessions",
    "public"."telegram_inbound_updates",
    "public"."threats",
    "public"."threat_scores",
    "public"."vehicle_logs",
    "public"."vehicle_visits",
    "public"."violations",
    "public"."watch_archive",
    "public"."watch_events",
    "public"."threat_decay_profiles",
    "public"."alert_rules",
    "public"."dispatch_actions",
    "public"."mo_library",
    "public"."intel_source_weights",
    "public"."global_patterns",
    "public"."staff",
    "public"."controllers",
    "public"."guard_assignments",
    "public"."operational_nodes",
    "public"."duty_states"
RESTART IDENTITY;

-- Delete public.patrol_triggers instead of truncating because non-wipe tables reference it directly or through delete-closure.
WITH deleted AS (
    DELETE FROM "public"."patrol_triggers"
    RETURNING 1
)
SELECT 'public.patrol_triggers deleted' AS action, count(*) AS rows FROM deleted;

-- Delete public.patrols instead of truncating because non-wipe tables reference it directly or through delete-closure.
WITH deleted AS (
    DELETE FROM "public"."patrols"
    RETURNING 1
)
SELECT 'public.patrols deleted' AS action, count(*) AS rows FROM deleted;

-- Delete public.employees instead of truncating because non-wipe tables reference it directly or through delete-closure.
WITH deleted AS (
    DELETE FROM "public"."employees"
    RETURNING 1
)
SELECT 'public.employees deleted' AS action, count(*) AS rows FROM deleted;

-- Delete public.guards instead of truncating because non-wipe tables reference it directly or through delete-closure.
WITH deleted AS (
    DELETE FROM "public"."guards"
    RETURNING 1
)
SELECT 'public.guards deleted' AS action, count(*) AS rows FROM deleted;

-- Delete public.posts instead of truncating because non-wipe tables reference it directly or through delete-closure.
WITH deleted AS (
    DELETE FROM "public"."posts"
    RETURNING 1
)
SELECT 'public.posts deleted' AS action, count(*) AS rows FROM deleted;

COMMIT;
