import '../domain/intelligence/news_item.dart';
import '../domain/intelligence/decision_service.dart';
import '../domain/intelligence/intel_ingestion.dart';
import '../domain/authority/authority_token.dart';
import '../domain/authority/operator_context.dart';
import '../engine/execution/execution_engine.dart';
import '../domain/store/event_store.dart';
import '../domain/intelligence/risk_policy.dart';
import '../domain/events/decision_created.dart';
import '../domain/events/execution_completed.dart';
import '../domain/events/execution_denied.dart';
import '../domain/events/intelligence_received.dart';
import '../domain/projection/dispatch_projection.dart';
import '../domain/testing/replay_consistency_verifier.dart';
import '../domain/evidence/client_ledger_service.dart';
import '../domain/intelligence/triage_policy.dart';

class IntelligenceIngestionOutcome {
  final int attemptedIntelligence;
  final int appendedIntelligence;
  final int skippedIntelligence;
  final int createdDecisions;

  const IntelligenceIngestionOutcome({
    required this.attemptedIntelligence,
    required this.appendedIntelligence,
    required this.skippedIntelligence,
    required this.createdDecisions,
  });
}

class DispatchApplicationService {
  final EventStore store;
  final ExecutionEngine engine;
  final RiskPolicy policy;
  final IntelligenceTriagePolicy triagePolicy;
  final ClientLedgerService ledgerService;
  final OperatorContext operator;

  DispatchApplicationService({
    required this.store,
    required this.engine,
    required this.policy,
    this.triagePolicy = const IntelligenceTriagePolicy(),
    required this.ledgerService,
    required this.operator,
  });

  void _verifyReplay() {
    ReplayConsistencyVerifier.verify(store.allEvents());
  }

  void processIntelligenceDemo({
    required String clientId,
    required String regionId,
    required String siteId,
  }) {
    final news = NewsItem(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      title: 'Simulated High Risk',
      source: clientId,
      summary: 'Generated from UI',
      riskScore: 85,
      clientId: clientId,
      regionId: regionId,
      siteId: siteId,
    );

    final decisionService = DecisionService(policy);

    final DecisionCreated? decision = decisionService.evaluate(
      news,
      clientId: clientId,
      regionId: regionId,
      siteId: siteId,
    );

    if (decision == null) return;

    store.append(decision);
    _verifyReplay();
  }

  IntelligenceIngestionOutcome ingestNormalizedIntelligence({
    required List<NormalizedIntelRecord> records,
    bool autoGenerateDispatches = true,
    bool verifyReplay = true,
    Set<String>? existingDispatchIdsCache,
    Set<String>? existingIntelIdsCache,
  }) {
    final ingestion = DeterministicIntelligenceIngestionService(store: store);
    final ingestResult = ingestion.ingestBatch(
      records,
      existingIntelIds: existingIntelIdsCache,
    );
    final createdDecisions = autoGenerateDispatches
        ? _createDecisionsFromIntel(records, existingDispatchIdsCache)
        : 0;

    if (verifyReplay && (ingestResult.appended > 0 || createdDecisions > 0)) {
      _verifyReplay();
    }

    return IntelligenceIngestionOutcome(
      attemptedIntelligence: ingestResult.attempted,
      appendedIntelligence: ingestResult.appended,
      skippedIntelligence: ingestResult.skipped,
      createdDecisions: createdDecisions,
    );
  }

  void verifyReplayConsistency() {
    _verifyReplay();
  }

  bool escalateIntelligence(
    IntelligenceReceived intel, {
    bool verifyReplay = true,
  }) {
    final dispatchId = _dispatchIdForExternal(intel.provider, intel.externalId);
    final knownDispatchIds = store
        .allEvents()
        .whereType<DecisionCreated>()
        .map((event) => event.dispatchId)
        .toSet();
    if (knownDispatchIds.contains(dispatchId)) {
      return false;
    }

    store.append(
      DecisionCreated(
        eventId: 'DEC-MANUAL-$dispatchId',
        sequence: 0,
        version: 1,
        occurredAt: DateTime.now().toUtc(),
        clientId: intel.clientId,
        regionId: intel.regionId,
        siteId: intel.siteId,
        dispatchId: dispatchId,
      ),
    );
    if (verifyReplay) {
      _verifyReplay();
    }
    return true;
  }

  int _createDecisionsFromIntel(
    List<NormalizedIntelRecord> records,
    Set<String>? existingDispatchIds,
  ) {
    final knownDispatchIds =
        existingDispatchIds ??
        store
            .allEvents()
            .whereType<DecisionCreated>()
            .map((event) => event.dispatchId)
            .toSet();

    final ordered = [...records]
      ..sort((a, b) => a.occurredAtUtc.compareTo(b.occurredAtUtc));
    final historicalIntel = store
        .allEvents()
        .whereType<IntelligenceReceived>()
        .toList(growable: false);
    final knownDecisions = store
        .allEvents()
        .whereType<DecisionCreated>()
        .toList(growable: true);

    var created = 0;
    for (var index = 0; index < ordered.length; index++) {
      final record = ordered[index];
      final assessment = triagePolicy.evaluateNormalizedRecord(
        record: record,
        historicalIntel: historicalIntel,
        batchPeers: ordered
            .where((candidate) => !identical(candidate, record))
            .toList(growable: false),
        decisions: knownDecisions,
      );
      if (!assessment.shouldEscalate) {
        continue;
      }

      final dispatchId = _dispatchIdFor(record);
      if (knownDispatchIds.contains(dispatchId)) {
        continue;
      }

      final decision = DecisionCreated(
        eventId: 'DEC-$dispatchId',
        sequence: 0,
        version: 1,
        occurredAt: record.occurredAtUtc,
        clientId: record.clientId,
        regionId: record.regionId,
        siteId: record.siteId,
        dispatchId: dispatchId,
      );
      store.append(decision);
      knownDecisions.add(decision);
      knownDispatchIds.add(dispatchId);
      created++;
    }

    return created;
  }

  String _dispatchIdFor(NormalizedIntelRecord record) {
    return _dispatchIdForExternal(record.provider, record.externalId);
  }

  String _dispatchIdForExternal(String provider, String externalId) {
    final providerCode = _sanitize(provider).padRight(4, 'X').substring(0, 4);
    final extCode = _sanitize(externalId).padRight(8, '0').substring(0, 8);
    return 'DSP-$providerCode-$extCode';
  }

  String _sanitize(String raw) {
    final normalized = raw.toUpperCase().replaceAll(RegExp(r'[^A-Z0-9]'), '');
    if (normalized.isEmpty) return 'X';
    return normalized;
  }

  Future<void> execute({
    required String clientId,
    required String regionId,
    required String siteId,
    required String dispatchId,
  }) async {
    final projection = DispatchProjection();

    for (final event in store.allEvents()) {
      projection.apply(event);
    }

    final status = projection.statusOf(
      clientId: clientId,
      regionId: regionId,
      siteId: siteId,
      dispatchId: dispatchId,
    );

    if (status != 'DECIDED') return;

    // 🔒 Authority Boundary
    if (!operator.canExecute(regionId: regionId, siteId: siteId)) {
      final denied = ExecutionDenied(
        eventId: DateTime.now().microsecondsSinceEpoch.toString(),
        sequence: 0,
        version: 1,
        occurredAt: DateTime.now().toUtc(),
        dispatchId: dispatchId,
        clientId: clientId,
        regionId: regionId,
        siteId: siteId,
        operatorId: operator.operatorId,
        reason: 'Operator not authorized for region/site',
      );

      store.append(denied);
      _verifyReplay();
      return;
    }

    final authority = AuthorityToken(
      authorizedBy: operator.operatorId,
      timestamp: DateTime.now(),
    );

    engine.execute(dispatchId, authority: authority);

    final executionEvent = ExecutionCompleted(
      eventId: DateTime.now().microsecondsSinceEpoch.toString(),
      sequence: 0,
      version: 1,
      occurredAt: DateTime.now().toUtc(),
      clientId: clientId,
      regionId: regionId,
      siteId: siteId,
      dispatchId: dispatchId,
      success: true,
    );

    store.append(executionEvent);

    _verifyReplay();

    await ledgerService.sealDispatch(
      clientId: clientId,
      dispatchId: dispatchId,
      events: store.allEvents(),
    );
  }
}
